Controllers/TestAjaxBeginFormSearchPagedList1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC442.Models;
using PagedList;
using MVC442.Models.ViewModel;

namespace MVC442.Controllers {
    public class TestAjaxBeginFormSearchPagedList1Controller : Controller {
        private mvc442Entities db = new mvc442Entities();

        //
        // GET: /TestAjaxBeginForm5/

        public ActionResult Index(WebLinkCasinoCriteria model) {
 
            int pageIndex = model.Page ?? 1;
    
            model.WebLinkCasinoVMList = (from w in db.WebLinkCasinoes.Where(f =>
                         (String.IsNullOrEmpty(model.WebName) || f.WebName.Contains(model.WebName))
                         &&  (String.IsNullOrEmpty(model.Description) || f.Description.Contains(model.Description))
                         ).OrderByDescending(f => f.IdCon)
                               select new WebLinkCasinoVM {
                                   IdCon = w.IdCon,
                                   WebName = w.WebName,
                                   Description = w.Description 

                               }).ToPagedList(pageIndex, 5);

 

            if (Request.IsAjaxRequest()) {
                return PartialView("_PartialView", model);
            } else {
                return View(model);
            }  
             
        }

         
    

    }
}

Views/TestAjaxBeginFormSearchPagedList1/Index.cshtml
@model  MVC442.Models.ViewModel.WebLinkCasinoCriteria 
@{ 
    Layout = null;
}

<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script>
    //\\\\\\\ JS  retrun message SucccessPost or FailPost
    function SuccessMessage(result) {
        $("#ajax-main").html(result);
        alert("Succcess Post");
    }
    function FailMessage() {
        alert("Fail Post");
    }
</script>

<h1>Search</h1> 

@using (Ajax.BeginForm("Index", "TestAjaxBeginFormSearchPagedList1", null, 
    new AjaxOptions {
    HttpMethod = "POST",
    OnSuccess = "SuccessMessage",
    OnFailure = "FailMessage" ,
    UpdateTargetId = "resultTarget",// Set  ID  For Update Data  
    InsertionMode = InsertionMode.Replace,
    //  LoadingElementId = "loader" //  Set  ID & image .gif (To shown when data  loading )
} // , new { id = "MyNewNameId" })) // Set Custom name Id for Form 
))
{
        @Html.AntiForgeryToken()
     
        @Html.LabelFor(x => x.WebName) @: 
        @Html.EditorFor(x => x.WebName)    <span>  </span>
        @Html.LabelFor(x => x.Description) @:
        @Html.EditorFor(x => x.Description)    <span>  </span>
        <input type="submit" value="Search" /> 
    
}
 
<div id="resultTarget"> </div>

 

Views/TestAjaxBeginFormSearchPagedList1/_PartialView.cshtml
@using PagedList;
@using PagedList.Mvc;

@model MVC442.Models.ViewModel.WebLinkCasinoCriteria 

<table>  
       <td>@Html.DisplayNameFor(model => model.IdCon  )</td>
      <td>@Html.DisplayNameFor(model => model.WebName)</td>
        <td>@Html.DisplayNameFor(model => model.Description)</td> 

@foreach (var item in Model.WebLinkCasinoVMList ) {   
    <tr> 
        <td>@Html.DisplayFor(modelItem => item.IdCon)</td>  
        <td>@Html.DisplayFor(modelItem => item.WebName)</td>    
        <td>@Html.DisplayFor(modelItem => item.Description)</td> 
    </tr> 
}

</table>

 
@Html.PagedListPager(Model.WebLinkCasinoVMList ,page=> Url.Action("Index",new RouteValueDictionary
{
    {"Page",page},
    {"WebName",Model.WebName}, // Add RouteValue For Rember FilterParamiter  
    {"Description",Model.Description}  // Add RouteValue For Rember FilterParamiter  
}),PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions{ UpdateTargetId="resultTarget"}))