Controllers/TestAjaxBeginFormCreateUpdateDeleteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC442.Models;
using MVC442.Models.ViewModel;
using System.Data;

namespace MVC442.Controllers
{
    public class TestAjaxBeginFormCreateUpdateDeleteController : Controller
    {
        mvc442Entities db = new mvc442Entities();

        public ActionResult Index()  {
            var model = db.ClientMessages.ToList(); 
            return View(model) ;
        }

        public ActionResult Create(int id=0)  { 

            var VmModel = new ClientMessageVM();
            return View(VmModel); 
        }
        
        
        [HttpPost]
        public ActionResult Create(ClientMessage VM )  {
  
   ClientMessage model = new ClientMessage();
            if (ModelState.IsValid) {
                    model.Name = VM.Name;
                    model.Message = VM.Message;

                db.ClientMessages.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index"); 
              } 

             return View(VM);
        }

        public ActionResult Edit(int id = 0) {
            ClientMessage clientMessage = db.ClientMessages.Find(id);

            var VmModel = new ClientMessageVM {
                IdCon = clientMessage.IdCon,
                Name = clientMessage.Name,
                Message = clientMessage.Message

            };

            return View(VmModel);
        }


        [HttpPost]
        public ActionResult Edit(ClientMessage VM) {
            ClientMessage clientMessages = db.ClientMessages.Find(VM.IdCon);

            clientMessages.Name = VM.Name;
            clientMessages.Message = VM.Message;

            //////  Insert to database
            db.Entry(clientMessages).State = EntityState.Modified;
            db.SaveChanges();
            return View();

        }


    }
}

Views/TestAjaxBeginFormCreateUpdateDelete/Create.cshtml
@model MVC442.Models.ViewModel.ClientMessageVM 
@{ 
    Layout = null;
}

<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
 
<script>
    //\\\\\\\ JS  retrun message SucccessPost or FailPost 
    function SuccessMessage(){
        alert("Succcess Post");
    }
     function FailMessage(){
        alert("Fail Post");
    }

</script>
 
<h2>Create</h2>

@*  /////////////////////  Use AJAX Form  *@
@using (Ajax.BeginForm("create", "TestAjaxBeginFormCreateUpdateDelete", null,  // Add ActionName  , Controller , RouteValues
    new AjaxOptions {
        HttpMethod = "POST" , 
        OnSuccess = "SuccessMessage", 
        OnFailure = "FailMessage"
        // UpdateTargetId = "resultTarget" , // Set  ID  For Update Data  
        // InsertionMode = InsertionMode.Replace, 
        // LoadingElementId = "loader" //  Set  ID & image .gif (To shown when data  loading )

    }//, new { id = "MyNewNameId" } // Set Custom name Id for Form
            
        ))  
    { 
    
   
    @Html.ValidationSummary(true)
 
    <div class="editor-field">
        @Html.EditorFor(model => model.IdCon) 
    </div>  
    <div class="editor-label">
        @Html.LabelFor(model => model.Name)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div> 
    <div class="editor-label">
        @Html.LabelFor(model => model.Message)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Message)
        @Html.ValidationMessageFor(model => model.Message)
    </div>  
    <div class="editor-label">
    </div>
    <div class="editor-field">
        <input type="submit" value="Create" />
            @Html.ActionLink("Back to List", "Index") 
    </div>  
    
}
 
 @*
<div id="loader" class=" aletr" style="display:none">
Loading...<img src="~/Images/ajax-loader.gif" />
</div>
*@ 

 
@* 
<div id="resultTarget"></div>  <!-- Update Data Here -->
*@




 

Views/TestAjaxBeginFormCreateUpdateDelete/Edit.cshtml
@model MVC442.Models.ViewModel.ClientMessageVM 
@{ 
    Layout = null;
}

<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
 
<script>
    //\\\\\\\ JS  retrun message SucccessPost or FailPost 
    function SuccessMessage(){
        alert("Succcess Post");
    }
     function FailMessage(){
        alert("Fail Post");
    }

</script>

<h2>Edit</h2>

@*  /////////////////////  Use AJAX Form  *@
@using (Ajax.BeginForm("Edit", "TestAjaxBeginFormCreateUpdateDelete", null,  // Add ActionName  , Controller , RouteValues
    new AjaxOptions {
        HttpMethod = "POST" , 
        OnSuccess = "SuccessMessage", 
        OnFailure = "FailMessage"
        // UpdateTargetId = "resultTarget" , // Set  ID  For Update Data  
        // InsertionMode = InsertionMode.Replace, 
        // LoadingElementId = "loader" //  Set  ID & image .gif (To shown when data  loading )

    }//, new { id = "MyNewNameId" } // Set Custom name Id for Form
            
        ))  
    { 
    
    @Html.ValidationSummary(true) 
    
    <div class="editor-field">
        @Html.EditorFor(model => model.IdCon) 
    </div>  
    <div class="editor-label">
        @Html.LabelFor(model => model.Name)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </div> 
    <div class="editor-label">
        @Html.LabelFor(model => model.Message)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Message)
        @Html.ValidationMessageFor(model => model.Message)
    </div> 
    <div class="editor-label">
    </div>
    <div class="editor-field">
        <input type="submit" value="Edit" />
        @Html.ActionLink("Back to List", "Index") 
    </div> 

}
 
 @*
<div id="loader" class=" aletr" style="display:none">
Loading...<img src="~/Images/ajax-loader.gif" />
</div>
*@ 

 
@* 
<div id="resultTarget"></div>  <!-- Update Data Here -->
*@

Views/TestAjaxBeginFormCreateUpdateDelete/Index.cshtml
@model IEnumerable<MVC442.Models.ClientMessage>

@{
    Layout = null;
}

     @Html.ActionLink("Create", "Create" ) 
 
    <table>
        <tr>
            <th> @Html.DisplayNameFor(model => model.IdCon)  </th> 
            <th>  @Html.DisplayNameFor(model => model.Name) </th> 
            <th>  @Html.DisplayNameFor(model => model.Message) </th> 
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td> @Html.DisplayFor(modelItem => item.IdCon) </td> 
            <td> @Html.DisplayFor(modelItem => item.Name)  </td> 
            <td>  @Html.DisplayFor(modelItem => item.Message)  </td> 
            <td>  @Html.ActionLink("Edit", "Edit", new {   id=item.IdCon  })  </td>
        </tr>
    }
    
    </table>
 