Controllers/TestAjaxBeginFormCreate_PartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC442.Models;
using MVC442.Models.ViewModel; 

namespace MVC442.Controllers
{
    public class TestAjaxBeginFormCreate_PartialController : Controller
    {

   
        mvc442Entities db = new mvc442Entities();

        public ActionResult index()
        {
           // ModelState.AddModelError(string.Empty, "Now You Use AJAX Post"); // Set show error from ModelState
            return RedirectToAction("Create");
               
        }

      
        public ActionResult Create( ) {
            ClientMessageVM VM = new ClientMessageVM();

            return View(VM);
        }

         [HttpPost]
        public ActionResult Create(ClientMessageVM VM) {

           if (  !string.IsNullOrEmpty( VM.Name ) ||  !string.IsNullOrEmpty(VM.Message) ) {
                    ClientMessage model = new ClientMessage();
                    model.Name =  VM.Name ;
                    model.Message =   VM.Message;

                    db.ClientMessages.Add(model);
                    db.SaveChanges();
                                                 

                var model2 = db.ClientMessages.Select( x => new ClientMessageVM {
                    Name = x.Name ,
                    Message = x.Message 
                }).ToList() ;

         

                return PartialView("_PartialView", model2 );  // Return Result to  PartialView  
          }
              
            return View(VM); 
        }
 
 

    }
}

Views/TestAjaxBeginFormCreate_Partial/Create.cshtml
@model  MVC442.Models.ViewModel.ClientMessageVM 
@{
    Layout = null;
}

<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script>
    //\\\\\\\ JS  retrun message SucccessPost or FailPost
    function SuccessMessage() {
        alert("Succcess Post");
    }
    function FailMessage() {
        alert("Fail Post");
    }
</script>

<h1>Ajax Create </h1> 

@using (Ajax.BeginForm("Create", "TestAjaxBeginFormCreate_Partial", new AjaxOptions {
        HttpMethod = "POST",
        OnSuccess = "SuccessMessage",
        OnFailure = "FailMessage" ,
        UpdateTargetId = "resultTarget",  // Set  ID  For Update Data  
        //InsertionMode = InsertionMode.Replace 
        // LoadingElementId = "loader" //  Set  ID & image .gif (To shown when data  loading )
    }  //, new { id = "MyNewNameId" } // Set Custom name Id for Form
    ))
{ 
 
        @Html.AntiForgeryToken()  
 
    
    <div class="editor-label">
        @Html.LabelFor(model => model.Name)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Name) 
    </div> 
    <div class="editor-label">
        @Html.LabelFor(model => model.Message)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Message) 
    </div>  
 
        <input type="submit" value="Create" /> 
    
    
} 




@*
<div id="loader" class=" aletr" style="display:none">
Loading...<img src="~/Images/ajax-loader.gif" />
</div>
*@ 

 <div id="resultTarget">  </div>  <!-- Update Data Here -->

Views/TestAjaxBeginFormCreate_Partial/_PartialView.cshtml
@model  IEnumerable<MVC442.Models.ViewModel.ClientMessageVM>
<table> 
       <tr> 
        <td>@Html.DisplayNameFor(model => model.IdCon)</td>
     <td>@Html.DisplayNameFor(model => model.Name)</td>
            <td>@Html.DisplayNameFor(model => model.Message)</td> 
                   
    </tr>

@foreach (var item in Model) { 
    
    <tr> 
        <td>@Html.DisplayFor(modelItem => item.IdCon)</td>
          <td>@Html.DisplayFor(modelItem => item.Name)</td>
        <td>@Html.DisplayFor(modelItem => item.Message)</td> 
    </tr>
    
}

</table>