Controllers/TestPatialDropDown3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//======================
using MVC442.Models;
using MVC442.Models.ViewModel;



namespace MVC442.Controllers
{
    public class TestPatialDropDown3Controller : Controller {
        private mvc442Entities db = new mvc442Entities();

        
 
        public ActionResult index(int id = 0)
        {

            var VM = new BaseVM();  // Get Field SelectListItems  From Empty BaseVM 
            VM.SelectListItems = GetCasinoCat();  // Get SelectListItems by  Method GetCasinoCats()
            return View(VM);
        }
         
        public IEnumerable<SelectListItem> GetCasinoCat()
        {
            var SelectListItemCasinoCats = db.CasinoCats.ToList() //  Set ToList here - FIX  LINQ to Entity not support  .ToString()
                .OrderBy(x => x.IdCasinoCat)
                .Select(x => new SelectListItem() { Text = x.CatNameTh, Value = x.IdCasinoCat.ToString() });
            return SelectListItemCasinoCats;
        }



    }
}

Views/TestPatialDropDown3/Create.cshtml
@model MVC442.Models.ViewModel.WebLinkCasinoVM

@{
    Layout = "~/Views/Shared/_Layout442-Backend1.cshtml";
    ViewBag.Title = "Create";
    string reqType = Request.QueryString["type"];
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    
  
    
        <div class="editor-label">
            @Html.LabelFor(model => model.IdCasinoCat, "CasinoCat")
        </div>
        <div class="editor-field"> 
         

        @* ////// DropDown By @Html.Action  //////*@
        @Html.Action("CasinoCatPartial", "WebLinkCasino", new { DdlId = "myCustomName1", IdCasinoCat = Model.IdCasinoCat  ,type = reqType  })
        @Html.ValidationMessageFor(model => model.IdCasinoCatSelected)

        </div>
    
    
    
    
        @Html.HiddenFor(model => model.ConType)
 

        <div class="editor-label">
            @Html.LabelFor(model => model.WebName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.WebName)
            @Html.ValidationMessageFor(model => model.WebName)
        </div>
    
    
        <div class="editor-label">
            @Html.LabelFor(model => model.WebLink)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.WebLink)
            @Html.ValidationMessageFor(model => model.WebLink)
        </div>
     
        <div class="editor-label"> 
        </div>
        <div class="editor-field">
        <input type="submit" value="Create"   class="btnDefault" />
        @Html.ActionLink("Back to List", "Index" ,  new { type = reqType }  , new {@class="btnDefault"  } )
        </div>
    
}

 

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/TestPatialDropDown3/Edit.cshtml
@using CaptchaMvc.HtmlHelpers

@model MVC442.Models.ViewModel.WebLinkCasinoVM

@{
    Layout = "~/Views/Shared/_Layout442-Backend1.cshtml";
    ViewBag.Title = "Edit";

    string reqType = Request.QueryString["type"];
}

@{
    //// Get PageName from   Request.QueryString[ ] //////
    if (reqType == "2") {
    @:<h2>Sport Online - Edit </h2>
     }
    else {
    @:<h2>Casino Online - Edit </h2>
    }
    
}


@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)  
    <div class="editor-label">
        @Html.LabelFor(model => model.IdCon)
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.IdCon)
        @Html.HiddenFor(model => model.IdCon)
    </div> 
    
    <div class="editor-label">
        @Html.LabelFor(model => model.IdCasinoCat, "CasinoCat")
    </div> 
    <div class="editor-field"> 

        @* ////// DropDown By @Html.Action  //////*@
        @Html.Action("CasinoCatPartial", "TestPatialDropDown3", new { DdlId = "myCustomName1", IdCasinoCat = Model.IdCasinoCat , type = reqType  }) 

        @Html.ValidationMessageFor(model => model.IdCasinoCatSelected)
    </div>
    
     
    
    @Html.HiddenFor(model => model.ConType)

 
    <div class="editor-label">
        @Html.LabelFor(model => model.WebName)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.WebName)
        @Html.ValidationMessageFor(model => model.WebName)
    </div>
 
  
    <div class="editor-label">
    </div>
    <div class="editor-field">
        <input type="submit" value="Save" class="btnDefault" />
        @Html.ActionLink("Back to List", "Index", new { type = reqType }, new { @class = "btnDefault" })
    </div>
          
      
    
}
 

Views/TestPatialDropDown3/Index.cshtml
@{
    Layout = null; 
}
<h3> DropDownListFor by @@Html.Partial( )  </h3>


@Html.Partial("_PartialView")  

Views/TestPatialDropDown3/_PartialView.cshtml
@*/// Get Field SelectListItems  From Empty BaseVM   *@ 
@model MVC442.Models.ViewModel.BaseVM   
  
  
@Html.DropDownListFor(model => model.SelectListItems ,  new SelectList(Model.SelectListItems , "Value", "Text") , "======= Select ========", new { @class = "select" }) 
 